### ISSUE TITLE
route defaults

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/hapi-auto-loader#2]
be able to set defaults that get applied to all routes

**Comment by dawnerd** [comment]
Do you want to be able to pass in an object to the options, or have a method you can call that sets default values (like server.expose)

**Comment by jgallen23** [comment]
I initially thought of just passing an object to the loader.  We should also consider allowing for route prefixes, so you could prefix all routes loaded with something like `/api/`

**Comment by dawnerd** [comment]
latest commit added this in for ya!
