### ISSUE TITLE
route path from dir name

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/hapi-auto-loader#9]
what do you think about having routes automatically prefixed by their directory name.  So if you the file: `routes/api/index.js`

it would auto prefix all routes in that directory with `api`

**Comment by jgallen23** [comment]
@dawnerd @ecwillis thoughts?

**Comment by dawnerd** [comment]
:+1: 

Been wanting to add this in actually.

**Comment by ecwillis** [comment]
That would be awesome
